name: customaction
description: "first action"
inputs:
  name: 
    default: "rajat"
runs:
  using: "composite"
  steps: 
    - name: task1
      env: 
        name: ${{inputs.name}}
      run: |
        echo "composite action and version 2.0 is ready."
        echo "Your name is ${{env.name}}"
      shell: bash
