name: customaction
on: workflow_call
description: "first action"

runs:
  using: "composite"
  steps: 
    - name: task1
      run: echo "composite action and version 2.0 is ready."
      shell: bash
